import chest1 from '../../../assets/exercises/chest/wyciskaniesztangiplaska2.jpg';
import chest2 from '../../../assets/exercises/chest/wyciskaniesztangiplaska3.jpg';
import chest3 from '../../../assets/exercises/chest/wyciskaniesztangielki2.jpg';
import chest4 from '../../../assets/exercises/chest/wyciskaniesztangielki3.jpg';
import chest5 from '../../../assets/exercises/chest/motyl1.jpg';
import chest6 from '../../../assets/exercises/chest/motyl2.jpg';
import back1 from '../../../assets/exercises/back/2plecy1.jpg';
import back2 from '../../../assets/exercises/back/2plecy2.jpg';
import back3 from '../../../assets/exercises/back/4plecy1.jpg';
import back4 from '../../../assets/exercises/back/4plecy2.jpg';
import back5 from '../../../assets/exercises/back/14plecy1.jpg';
import back6 from '../../../assets/exercises/back/14plecy2.jpg';
import legs1 from '../../../assets/exercises/legs/1nogi1.jpg';
import legs2 from '../../../assets/exercises/legs/1nogi2.jpg';
import legs3 from '../../../assets/exercises/legs/12nogi1.jpg';
import legs4 from '../../../assets/exercises/legs/12nogi2.jpg';
import legs5 from '../../../assets/exercises/legs/14nogi2.jpg';
import legs6 from '../../../assets/exercises/legs/14nogi2.jpg';

export const pics = {chest1, chest2, chest3, chest4, chest5, chest6, back1, back2, back3, back4, back5, back6, legs1, legs2, legs3, legs4, legs5, legs6};
